# -*- coding: utf-8 -*-
# Generated by Django 1.10 on 2017-07-15 00:50
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('cart', '0006_auto_20170713_1240'),
    ]

    operations = [
        migrations.AlterField(
            model_name='cart',
            name='tax_total',
            field=models.DecimalField(decimal_places=2, default=25.0, max_digits=50, null=True),
        ),
    ]
