# -*- coding: utf-8 -*-
# Generated by Django 1.10 on 2017-07-17 06:00
from __future__ import unicode_literals

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('cart', '0007_auto_20170715_0050'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='cart',
            name='tax_total',
        ),
    ]
