# -*- coding: utf-8 -*-
# Generated by Django 1.10 on 2017-01-19 19:42
from __future__ import unicode_literals

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('stock', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Customer',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('firstname', models.CharField(max_length=50)),
                ('lastname', models.CharField(max_length=50)),
                ('contact', models.CharField(max_length=100)),
            ],
        ),
        migrations.CreateModel(
            name='Product',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=100)),
                ('price', models.PositiveIntegerField()),
                ('quantity', models.PositiveIntegerField()),
                ('buying_price', models.PositiveIntegerField()),
                ('category', models.CharField(max_length=100)),
                ('description', models.CharField(max_length=200)),
                ('size', models.CharField(max_length=50)),
            ],
        ),
        migrations.RenameModel(
            old_name='suppliers',
            new_name='Supplier',
        ),
        migrations.DeleteModel(
            name='products',
        ),
        migrations.RenameField(
            model_name='supplier',
            old_name='product',
            new_name='item',
        ),
        migrations.AddField(
            model_name='product',
            name='supplier',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='stock.Supplier'),
        ),
        migrations.AddField(
            model_name='customer',
            name='product',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='stock.Product'),
        ),
    ]
