# -*- coding: utf-8 -*-
# Generated by Django 1.10 on 2017-01-22 09:58
from __future__ import unicode_literals

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('stock', '0006_auto_20170122_0957'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='product',
            name='category',
        ),
        migrations.DeleteModel(
            name='Variation',
        ),
    ]
