# -*- coding: utf-8 -*-
# Generated by Django 1.10 on 2017-02-10 10:05
from __future__ import unicode_literals

from django.db import migrations, models
import stock.models


class Migration(migrations.Migration):

    dependencies = [
        ('stock', '0013_auto_20170122_1043'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='category',
            name='description',
        ),
        migrations.RemoveField(
            model_name='product',
            name='description',
        ),
        migrations.AlterField(
            model_name='productimage',
            name='image',
            field=models.ImageField(blank=True, null=True, upload_to=stock.models.upload_to),
        ),
    ]
