# -*- coding: utf-8 -*-
# Generated by Django 1.10 on 2017-02-11 11:11
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('stock', '0017_auto_20170211_1110'),
    ]

    operations = [
        migrations.AlterField(
            model_name='product',
            name='size',
            field=models.CharField(choices=[('s', 'small'), ('m', 'medium'), ('l', 'large'), ('xl', 'extra large'), ('xxl', 'extra x large'), (32, '32'), (34, '34'), (36, '36'), (38, '38'), (40, '40'), (42, '42')], max_length=5),
        ),
    ]
