# -*- coding: utf-8 -*-
# Generated by Django 1.10 on 2017-02-14 07:58
from __future__ import unicode_literals

from django.db import migrations, models
import stock.models


class Migration(migrations.Migration):

    dependencies = [
        ('stock', '0023_auto_20170213_0018'),
    ]

    operations = [
        migrations.CreateModel(
            name='Shoe',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('brand', models.CharField(max_length=50)),
                ('entry_date', models.DateField()),
                ('quantity', models.IntegerField()),
                ('size', models.CharField(choices=[(5, '5'), (6, '6'), (7, '7'), (7.5, '7.5'), (8.5, '8.5'), (9, '9'), (9.5, '9.5'), (10, '10'), (10.5, '10.5'), (11, '11'), (12, '12')], max_length=50)),
                ('shoe_image', models.ImageField(blank=True, null=True, upload_to=stock.models.upload_to)),
            ],
        ),
    ]
