# -*- coding: utf-8 -*-
# Generated by Django 1.10 on 2017-02-14 08:07
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('stock', '0024_shoe'),
    ]

    operations = [
        migrations.AlterField(
            model_name='shoe',
            name='size',
            field=models.CharField(choices=[(5, '5'), (6, '6'), (7, 7), (7.5, '7.5'), (8.5, '8.5'), (9, '9'), (9.5, '9.5'), (10, '10'), (10.5, '10.5'), (11, '11'), (12, '12')], max_length=50),
        ),
    ]
