# -*- coding: utf-8 -*-
# Generated by Django 1.10 on 2017-03-07 09:53
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('stock', '0027_auto_20170214_0829'),
    ]

    operations = [
        migrations.AddField(
            model_name='product',
            name='date',
            field=models.DateField(default='Jan. 01, 2017'),
        ),
        migrations.AddField(
            model_name='shoe',
            name='date',
            field=models.DateField(default='Jan. 01, 2017'),
        ),
    ]
