# -*- coding: utf-8 -*-
# Generated by Django 1.10 on 2017-03-07 09:54
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('stock', '0028_auto_20170307_0953'),
    ]

    operations = [
        migrations.AlterField(
            model_name='product',
            name='date',
            field=models.DateField(default='2017-01-01'),
        ),
        migrations.AlterField(
            model_name='shoe',
            name='date',
            field=models.DateField(default='2017-01-01'),
        ),
    ]
