# -*- coding: utf-8 -*-
# Generated by Django 1.10 on 2017-03-07 09:56
from __future__ import unicode_literals

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('stock', '0029_auto_20170307_0954'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='product',
            name='date',
        ),
        migrations.RemoveField(
            model_name='shoe',
            name='date',
        ),
    ]
