# -*- coding: utf-8 -*-
# Generated by Django 1.10 on 2017-03-07 10:01
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('stock', '0030_auto_20170307_0956'),
    ]

    operations = [
        migrations.AddField(
            model_name='product',
            name='date',
            field=models.DateField(auto_now_add=True, default=2015),
            preserve_default=False,
        ),
    ]
