# -*- coding: utf-8 -*-
# Generated by Django 1.10 on 2017-03-11 06:46
from __future__ import unicode_literals

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('stock', '0033_auto_20170311_0633'),
    ]

    operations = [
        migrations.RenameField(
            model_name='product',
            old_name='date',
            new_name='entry_date',
        ),
    ]
