# -*- coding: utf-8 -*-
# Generated by Django 1.10 on 2017-05-26 14:39
from __future__ import unicode_literals

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('stock', '0045_product_image'),
    ]

    operations = [
        migrations.AlterField(
            model_name='product',
            name='image',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='product_image', to='stock.ProductImage'),
        ),
        migrations.AlterField(
            model_name='product',
            name='size',
            field=models.CharField(choices=[('s', 'small'), ('m', 'medium'), ('l', 'large'), ('xl', 'extra large'), ('xxl', 'extra x large'), ('elastic', 'elastic'), (30, '30'), (32, '32'), (34, '34'), (36, '36'), (38, '38'), (40, '40'), (42, '42')], max_length=20),
        ),
    ]
