# -*- coding: utf-8 -*-
# Generated by Django 1.10 on 2017-05-30 08:15
from __future__ import unicode_literals

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('stock', '0047_auto_20170530_0536'),
    ]

    operations = [
        migrations.AlterModelManagers(
            name='category',
            managers=[
            ],
        ),
    ]
