# -*- coding: utf-8 -*-
# Generated by Django 1.10 on 2017-06-01 18:46
from __future__ import unicode_literals

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('stock', '0048_auto_20170530_0815'),
    ]

    operations = [
        migrations.CreateModel(
            name='CheckOut',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('contact', models.IntegerField()),
                ('residence', models.CharField(max_length=50)),
                ('size', models.CharField(max_length=20)),
                ('checkouitem', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='stock.Product')),
            ],
        ),
    ]
