# -*- coding: utf-8 -*-
# Generated by Django 1.10 on 2017-06-18 06:00
from __future__ import unicode_literals

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('stock', '0049_checkout'),
    ]

    operations = [
        migrations.RenameField(
            model_name='order',
            old_name='item',
            new_name='size',
        ),
    ]
