# -*- coding: utf-8 -*-
# Generated by Django 1.10 on 2017-06-18 11:38
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('stock', '0053_auto_20170618_1105'),
    ]

    operations = [
        migrations.AddField(
            model_name='product',
            name='details',
            field=models.CharField(blank=True, default='branded', max_length=50, null=True),
        ),
    ]
