# -*- coding: utf-8 -*-
# Generated by Django 1.10 on 2017-06-19 05:41
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('stock', '0054_product_details'),
    ]

    operations = [
        migrations.AlterField(
            model_name='product',
            name='size',
            field=models.CharField(choices=[('small', 's'), ('medium', 'm'), ('large', 'l'), ('extra large', 'xl'), ('extra x large', 'xxl'), ('elastic', 'elastic'), (30, '30'), (32, '32'), (34, '34'), (36, '36'), (38, '38'), (40, '40'), (42, '42')], max_length=20),
        ),
    ]
