# -*- coding: utf-8 -*-
# Generated by Django 1.10 on 2017-06-19 06:01
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('stock', '0056_auto_20170619_0559'),
    ]

    operations = [
        migrations.AlterField(
            model_name='product',
            name='size',
            field=models.CharField(choices=[('xs', 'extra small'), ('s', 'small'), ('m', 'medium'), ('l', 'large'), ('xl', 'extra large'), ('xxl', 'extra x large'), ('elastic', 'elastic'), ('30', 'waist 30'), ('32', 'waist 32'), ('34', 'waist 34'), ('36', 'waist 36'), ('38', 'waist 38'), ('40', 'waist 40'), ('42', 'waist 42')], default='elastic', max_length=20),
        ),
    ]
