# -*- coding: utf-8 -*-
# Generated by Django 1.10 on 2017-06-19 09:27
from __future__ import unicode_literals

from django.db import migrations, models
import stock.models


class Migration(migrations.Migration):

    dependencies = [
        ('stock', '0058_auto_20170619_0608'),
    ]

    operations = [
        migrations.AlterField(
            model_name='productimage',
            name='image',
            field=models.ImageField(blank=True, height_field=171, null=True, upload_to=stock.models.upload_to, width_field=180),
        ),
    ]
