# -*- coding: utf-8 -*-
# Generated by Django 1.10 on 2017-06-20 21:01
from __future__ import unicode_literals

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('stock', '0060_auto_20170619_0930'),
    ]

    operations = [
        migrations.DeleteModel(
            name='Shoe',
        ),
    ]
