# -*- coding: utf-8 -*-
# Generated by Django 1.10 on 2017-06-23 13:51
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('stock', '0061_delete_shoe'),
    ]

    operations = [
        migrations.AddField(
            model_name='product',
            name='status',
            field=models.CharField(choices=[('y', 'yes'), ('n', 'no')], default='y', max_length=10),
        ),
    ]
