# -*- coding: utf-8 -*-
# Generated by Django 1.10 on 2017-07-05 10:38
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('stock', '0063_auto_20170705_0806'),
    ]

    operations = [
        migrations.CreateModel(
            name='Checkout',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(blank=True, max_length=50, null=True)),
                ('size', models.CharField(blank=True, max_length=50, null=True)),
                ('price', models.IntegerField(blank=True, null=True)),
                ('quantity', models.PositiveIntegerField(default=1, null=True)),
                ('contact', models.IntegerField(null=True)),
            ],
        ),
        migrations.DeleteModel(
            name='Order',
        ),
    ]
