# -*- coding: utf-8 -*-
# Generated by Django 1.10 on 2017-08-21 08:07
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('stock', '0066_auto_20170818_0827'),
    ]

    operations = [
        migrations.AddField(
            model_name='customer',
            name='timestamp',
            field=models.DateTimeField(auto_now_add=True, default=1),
            preserve_default=False,
        ),
        migrations.AlterField(
            model_name='customer',
            name='contact',
            field=models.PositiveIntegerField(),
        ),
    ]
