# -*- coding: utf-8 -*-
# Generated by Django 1.10 on 2017-08-21 08:15
from __future__ import unicode_literals

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('stock', '0067_auto_20170821_0807'),
    ]

    operations = [
        migrations.RenameField(
            model_name='customer',
            old_name='timestamp',
            new_name='created',
        ),
    ]
