# -*- coding: utf-8 -*-
# Generated by Django 1.10 on 2017-08-21 08:48
from __future__ import unicode_literals

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('stock', '0068_auto_20170821_0815'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='customer',
            name='product',
        ),
    ]
