# -*- coding: utf-8 -*-
# Generated by Django 1.10 on 2017-08-21 12:14
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('stock', '0073_auto_20170821_1113'),
    ]

    operations = [
        migrations.AddField(
            model_name='customer',
            name='size',
            field=models.CharField(blank=True, max_length=10, null=True),
        ),
    ]
