# -*- coding: utf-8 -*-
# Generated by Django 1.10 on 2017-08-24 05:59
from __future__ import unicode_literals

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('stock', '0074_customer_size'),
    ]

    operations = [
        migrations.CreateModel(
            name='Shoe',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=20)),
                ('buying_price', models.PositiveIntegerField()),
                ('price', models.PositiveIntegerField()),
                ('size', models.CharField(max_length=20)),
                ('image', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='shoe_image', to='stock.ProductImage')),
            ],
        ),
    ]
