# -*- coding: utf-8 -*-
# Generated by Django 1.10 on 2017-08-27 10:27
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('stock', '0075_shoe'),
    ]

    operations = [
        migrations.AddField(
            model_name='customer',
            name='product',
            field=models.CharField(max_length=20, null=True),
        ),
    ]
