# -*- coding: utf-8 -*-
# Generated by Django 1.10 on 2017-09-22 08:39
from __future__ import unicode_literals

import datetime
from django.db import migrations, models
from django.utils.timezone import utc


class Migration(migrations.Migration):

    dependencies = [
        ('stock', '0076_customer_product'),
    ]

    operations = [
        migrations.AlterField(
            model_name='product',
            name='entry_date',
            field=models.DateTimeField(default=datetime.datetime(2017, 9, 22, 8, 39, 36, 578139, tzinfo=utc)),
        ),
    ]
