# -*- coding: utf-8 -*-
# Generated by Django 1.10 on 2017-09-28 19:17
from __future__ import unicode_literals

import datetime
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('stock', '0081_auto_20170924_0840'),
    ]

    operations = [
        migrations.AlterField(
            model_name='product',
            name='entry_date',
            field=models.DateField(default=datetime.date(2017, 9, 28)),
        ),
    ]
