# -*- coding: utf-8 -*-
# Generated by Django 1.10 on 2017-09-28 19:29
from __future__ import unicode_literals

import datetime
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('stock', '0082_auto_20170928_1917'),
    ]

    operations = [
        migrations.AlterField(
            model_name='product',
            name='entry_date',
            field=models.DateField(default=datetime.date.today),
        ),
    ]
