# -*- coding: utf-8 -*-
# Generated by Django 1.10 on 2017-07-11 03:36
from __future__ import unicode_literals

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('orders', '0004_auto_20170711_0331'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='useraddress',
            name='shipping_address',
        ),
    ]
