# -*- coding: utf-8 -*-
# Generated by Django 1.10 on 2017-09-22 08:37
from __future__ import unicode_literals

import datetime
from django.db import migrations, models
from django.utils.timezone import utc


class Migration(migrations.Migration):

    dependencies = [
        ('orders', '0010_auto_20170824_0559'),
    ]

    operations = [
        migrations.AddField(
            model_name='order',
            name='date',
            field=models.DateTimeField(default=datetime.datetime(2017, 9, 22, 8, 36, 59, 450821, tzinfo=utc)),
        ),
    ]
