# -*- coding: utf-8 -*-
# Generated by Django 1.10 on 2017-09-22 18:44
from __future__ import unicode_literals

import datetime
from django.db import migrations, models
from django.utils.timezone import utc


class Migration(migrations.Migration):

    dependencies = [
        ('orders', '0014_auto_20170922_1843'),
    ]

    operations = [
        migrations.AlterField(
            model_name='order',
            name='date',
            field=models.DateTimeField(default=datetime.datetime(2017, 9, 22, 18, 44, 5, 773448, tzinfo=utc)),
        ),
    ]
