# -*- coding: utf-8 -*-
# Generated by Django 1.10 on 2017-09-28 19:17
from __future__ import unicode_literals

import datetime
from django.db import migrations, models
from django.utils.timezone import utc


class Migration(migrations.Migration):

    dependencies = [
        ('orders', '0016_auto_20170924_0840'),
    ]

    operations = [
        migrations.AlterField(
            model_name='order',
            name='date',
            field=models.DateTimeField(default=datetime.datetime(2017, 9, 28, 19, 17, 28, 265333, tzinfo=utc)),
        ),
    ]
