# -*- coding: utf-8 -*-
# Generated by Django 1.10 on 2017-10-04 09:43
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('orders', '0018_auto_20170928_1929'),
    ]

    operations = [
        migrations.AddField(
            model_name='guestcheckout',
            name='braintree_id',
            field=models.CharField(blank=True, max_length=120, null=True),
        ),
    ]
