# -*- coding: utf-8 -*-
# Generated by Django 1.10 on 2017-10-06 19:46
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('orders', '0020_auto_20171006_1913'),
    ]

    operations = [
        migrations.AlterField(
            model_name='order',
            name='order_id',
            field=models.CharField(blank=True, max_length=30, null=True),
        ),
    ]
