# -*- coding: utf-8 -*-
# Generated by Django 1.10 on 2017-10-10 23:21
from __future__ import unicode_literals

from django.db import migrations
import phonenumber_field.modelfields


class Migration(migrations.Migration):

    dependencies = [
        ('orders', '0022_remove_order_order_id'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='order',
            options={'ordering': ['-id']},
        ),
        migrations.AddField(
            model_name='useraddress',
            name='phone',
            field=phonenumber_field.modelfields.PhoneNumberField(max_length=128, null=True),
        ),
    ]
