# -*- coding: utf-8 -*-
# Generated by Django 1.10 on 2017-10-14 22:46
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('orders', '0023_auto_20171010_2321'),
    ]

    operations = [
        migrations.AddField(
            model_name='order',
            name='order_id',
            field=models.CharField(blank=True, max_length=10, null=True),
        ),
    ]
